# Generated by Django 5.1.1 on 2024-09-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("deadline",)},
        ),
    ]
