# Generated by Django 5.1.1 on 2024-09-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-is_done", "-created_at")},
        ),
    ]
